### ISSUE TITLE
RemoteFrames

### ISSUE THREAD

**Issue by franc444** [CoRE-RG/SignalsAndGateways#1]
Hi, 
In the example of majorNetwork in its omnetpp.ini file, there is a source app that sends remote frames but I am not sure which node will receive this? 
it is stated as: 

`**.Infotainment_nodes[0].sourceApp[0].idRemoteFrames = "2"`

so the sending node is Infotainment_nodes[0] but there is no receiving node, right?

**Comment by Musteblume** [comment]
Hi,
yes there is no destination node configured to consume this frame. But it gets forwarded from the Infotainment bus to the Antrieb bus. Therefore gateway2 is configured to receive the frame.
Hope this helps.
Regards

**Comment by franc444** [comment]
Thanks @Musteblume 
I can see that gateway1 is also configured to receive the frame as it might be consumed by one of the Antrieb nodes. I would like to understand more how the node will be configured to consume this remote frame?

**Comment by Musteblume** [comment]
Hi again,
my previous answer was not completely correct. 

The remote frame is requesting id 2 and should  therefore be consumed by Antrieb_nodes[0].sourceApp[0] which then sends a data frame with id 2. For a small example of this look into FiCo4OMNeT->examples->can->multipleSourceApps.

In case of the SignalsAndGateways->majorNetwork example there is a miscofiguration in gatway 1. It receives the ethernet frame (ctID 30) containing the remote frame id 2 but send it back to the network and not to the bus.

I will have a look what the cause of this misconfiguration is.
Regards

**Comment by Musteblume** [comment]
Hi,
i have fixed the problem. The fix will be released here with the next nightly. This are all the changes (in gatway1.ini):
```
Best regards
Philipp
...
33  **.gateway1.tte[0].TTvlinks[2].destination_gates = "gatewayApp.TTin"
...
42  **.gateway1.tte[0].TTvlinks[3].destination_gates = "phy[0].TTin"
...
49  **.gateway1.tte[0].phy[0].shaper.tt_buffers = "TTvlinks[0], TTvlinks[3]"
```

**Comment by franc444** [comment]
Thanks for the fix. 
I am still not sure which node will receive the remote frame? should not be consumed eventually by a sinkApp? in the multipleSourceApps example the remote frames are being transmitted between two nodes right? but the sinkApps do not record the statistics for the remote frame i.e. rxRF they only record for rxDF. 
Am I missing something here or there is an issue with the statistics recording?

**Comment by Musteblume** [comment]
Hi,
currently you can have one of two configs:
1. a trafficSource with the same id which gets triggered by the remote frame
